name: golfdraw
description: App para reservas de golfe multiplataforma
version: 0.1.0

environment:
<<<<<<< HEAD
  sdk: ">=3.2.0 <4.0.0"
=======
  sdk: ">=2.19.0 <3.0.0"
>>>>>>> f93ce25dc780ea0e5ce27ef66c319bc40f256084

dependencies:
  flutter:
    sdk: flutter
<<<<<<< HEAD
  cupertino_icons: ^1.0.6
  characters: 1.4.0
  meta: ^1.10.0
  vector_math: ^2.1.4
=======
  cupertino_icons: ^1.0.2
>>>>>>> f93ce25dc780ea0e5ce27ef66c319bc40f256084

flutter:
  uses-material-design: true
  assets:
    - assets/images/
<<<<<<< HEAD

dev_dependencies:
  flutter_lints: ^3.0.1
  material_color_utilities: ^0.11.1
=======
>>>>>>> f93ce25dc780ea0e5ce27ef66c319bc40f256084
