name: golfdraw
description: App para reservas de golfe multiplataforma
version: 0.1.0

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  characters: 1.4.0
  meta: ^1.10.0
  vector_math: ^2.1.4

flutter:
  uses-material-design: true
  assets:
    - assets/images/

dev_dependencies:
  flutter_lints: ^3.0.1
  material_color_utilities: ^0.11.1